### ISSUE TITLE
Prepare projet for Open source

### ISSUE THREAD

**Issue by jeanphibaconnais** [zenika-open-source/cheatsheets#1]
The aim of this issue is to prepare this project to be opensourced.

**Comment by SyedaMahamFahim** [comment]
Hello,

I have thoroughly reviewed the website and the corresponding GitHub repository. I have identified several areas where improvements are needed for documentation purposes:

- README.md should be updated to include essential links such as the live website link ([live website link](https://zenika-open-source.github.io/cheatsheets/#)), [installation instruction](https://zenika-open-source.github.io/cheatsheets/quick-start/), and a link to the contribute.md file, among others.
- The Contribution.md file should be updated to provide important details on how to set up the project. It would be beneficial to include a direct link from the live website to the contribute.md file. Currently, this information is available on the [live website](https://zenika-open-source.github.io/cheatsheets/quick-start/), but I had to discover it myself by navigating through the deployment section.
- In the Installation section, there should be clear instructions on how to set up the project. Users should be able to follow these instructions directly.
- Consider adding a GitHub icon to the website's header. This icon would allow people to easily navigate to the GitHub repository for the project.

If this task is still available, I am enthusiastic about contributing to it during the upcoming Hacktoberfest event. Please let me know how I can get involved and assist with these improvements.

Thank you.

**Comment by LiolluryZ** [comment]
Hello @SyedaMahamFahim , live version is online recently and we have to update those files. You can contribute updating readme and maybe contribute file by adding some useful information like link to quick-start cheatsheet and others uselful informations.

Feel free to open a branch/pull request to start this ticket !

I'm available if you need help or information about the project.

Thank you for contributing.

**Comment by SyedaMahamFahim** [comment]
Hi @LiolluryZ, thank you for reviewing my proposal. I have forked the repo, I plan to create a pull request during the month of October so that it can be counted towards Hacktoberfest.

**Comment by jeanphibaconnais** [comment]
Thanks @SyedaMahamFahim 🙏 Don't hesitate if you have any question

**Comment by liollury** [comment]
Close with #23
